# 約維安計畫：使用 Python 載入資料

> 第三十一週

![](shinzo_abe.png)

來源：<https://www.ettoday.net/news/20220708/2290245.htm>

In [1]:
import json
import pandas as pd
import requests
from bs4 import BeautifulSoup
import sqlite3

## 橫空出世的職業？

從 2012 年哈佛商業評論拋出資料科學家（Data scientist）是 21 世紀最性感的職業那刻起，資料科學（Data science）從美國向世界捲起瘋狂的浪潮，一直延續到 2017 年 Deep Mind 團隊的 Alpha Go；資料科學、大數據、人工智慧、機器學習與深度學習等字彙從報章雜誌與社群媒體向我們大量放送。從新創團隊、軟體公司、金融業、顧問業與製造業開始重新思索資料驅動（Data-driven）的策略制定，進而期望招募更多同時具備軟體工程與統計學兩個領域專長的資料科學家，造成就業市場的需求量大增，進而驅動了資料科學家的年薪接近 14 萬美金，一躍而成矽谷最具吸引力的職缺。

資料科學家並不是一個橫空出世的職業，90 年代風靡全美的電視喜劇六人行（Friends），其中一個主角 Chandler Bing（由 Matthew Perry 飾演），在劇中有一個設定非常有趣，那就是他的好朋友們永遠都記不住他從事什麼樣的工作。有一天他告訴老婆 Monica Geller（由 Courtney Cox 飾演），為了家庭收入著想他要回去做他原本的工作，這時 Monica 跟他說：

> I want you to do something you like, not statistical analysis and data reconfiguration.

如果 Chandler 晚 20 年從事他原本的工作，那麼職稱多半就是資料科學家，頂著這個最性感職業的光環，也許這位有點膚淺又憤世嫉俗的傢伙就不會這麼討厭他的工作了吧？

## 資料科學家的日常

那麼究竟資料科學家的工作職責是什麼？資料科學家面對的專案可能會包含下列這些工作內容：使用者的需求發想、與使用者討論需求規格，取得測試資料、載入環境、整理資料、使用圖形探索資料、利用模型預測、部署專案到正式環境最後是將專案的內容以淺顯易懂的方式與組織內部其他的團隊溝通及分享。

![](data-science.png)

來源：https://r4ds.had.co.nz/introduction.html

首先是載入資料，將常見資料格式，包含純文字檔案、試算表或關聯式資料庫管理系統中的資料表，透過各式模組、套件載入開發環境，完成資料科學的第一個里程碑；在順利取得資料之後，在掌控資料環節（Wrangle），透過對資料結構的認知將原型資料（Raw data）清理整併為緊實乾淨的形式（Tidy data），這樣一致且通用的資料樣式能夠讓資料科學團隊集中精力處理資料探索和資料預測相關的應用；一旦有了緊實整潔的資料，在探索資料環節，將透過利用視覺化模組和套件進行探索性資料分析，適當的探索性資料分析可以讓資料科學團隊挖掘潛藏的特徵，進而延展專案的範疇與洞見；在資料建模環節，引入統計分析與機器學習這個資料科學中最吸引人、加值程度最大的過程，在定義精確的問題下，演算法可以訓練已知資料來作為未知資料預測的依據；資料科學的最後一步是溝通，這是專案的關鍵部分，如果能夠有效地向合作部門（像是產品、行銷與管理團隊等）精準地傳達分析結果，將能顯著為資料科學專案的成果加值，提升資料科學團隊在組織內的價值。

## 資料科學專案的發起點

載入資料在資料科學專案中扮演發起點，如果這個資料科學專案目的是協助我們制定資料驅動的策略（Data-driven strategy），而非倚賴直覺，那麼為專案細心盤點資料來源與整理獲取方法，可以為將來的決策奠基穩固的基礎。資料常見來源包含：

- 純文字檔案
    - 非結構化純文字檔案
    - 結構化純文字檔案
        - CSV
        - JSON
        - HTML
- 試算表
- 關聯式資料庫管理系統中的資料表

## 使用 Python 載入純文字檔案

純文字檔案指的是只有文字所構成的電腦檔案，這代表其中不包含字型的樣式或段落標記等，這類型檔案最明顯的特性就是能夠使用最簡單的文字編輯器（例如 Windows 的「記事本」、macOS 的 TextEdit）直接開啟檢視。

純文字檔案涵蓋的範圍相當廣泛，能夠再區分為非結構化純文字檔案與結構化純文字檔案兩大類；而結構化純文字檔案亦能再細分出 JSON、CSV 與 HTML 等。

非結構化純文字檔案常用來儲存像是文章、劇本或系統日誌（System logs）等，例如儲存在工作目錄的經典電影「刺激 1995」簡介 the_shawshank_redemption_summaries.txt，我們使用內建的 `open()` 函數開啟檔案，並將檔案內容一列一列載入到 `list` 之中，為了讓開檔、讀檔與關檔的流程能夠一氣呵成，使用 `with` 敘述建立資源管理器的程式區塊。

In [2]:
text_file_path = "the_shawshank_redemption_summaries.txt"
with open(text_file_path) as file:
    the_shawshank_redemption_summaries = file.readlines()
print(the_shawshank_redemption_summaries)

['Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.\n', "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.\n", 'After the murder of his wife, hotshot banker Andrew Dufresne is sent to Shawshank Prison, where the usual unpleasantness occurs. Over the years, he retains hope and eventually gains the respect of his fellow inmates, especially longtime convict "Red" Redding, a black marketeer, and becomes influential within the prison. Eventually, Andrew achieves his ends on his own terms.\n', "Andy Dufresne is sent to Shawshank Prison for the murder of his wife and her secret lover. He is very isolated and lonely at first, but realizes there is something deep inside your body that people can't touch or get to....'HOPE'. Andy becomes friends with prison 'fixer' Red, and Andy epitomizes why it is crucial to have dreams. His spirit and determination lead us into a world full of imagination, one filled with courage and desire. Will Andy ever realize his dreams?\n", 'Bank Merchant Andy Dufresne is convicted of the murder of his wife and her lover, and sentenced to life imprisonment at Shawshank prison. Life seems to have taken a turn for the worse, but fortunately Andy befriends some of the other inmates, in particular a character known only as Red. Over time Andy finds ways to live out life with relative ease as one can in a prison, leaving a message for all that while the body may be locked away in a cell, the spirit can never be truly imprisoned.']

結構化純文字檔案指的是透過特定符號讓資料能夠系統性地儲存、讀取及處理，例如 JSON(JavaScript Object Notation) 可以透過大括號 `{}` 儲存鍵值對應的資料、CSV(Comma Separated Values) 可以透過逗號 `,` 分隔不同欄位、HTML(Hyper Text Markup Language) 可以透過標記 `<></>` 顯示不同外型與功能的資料。

JSON 是一種輕量的資料交換格式，對於人類而言是容易閱讀和寫作的格式，對於電腦而言是容易解析和建立的格式，簡言之，是一種對人類與電腦都友善的純文字格式，JSON 雖然源於 JavaScript，但卻是獨立於該程式語言之外，能夠被眾多程式語言輕鬆解析和建立的一種理想資料交換格式。JSON 可能由兩種資料結構組成：鍵值對應關係與有序列表，可以用 Python 的 `dict` 與 `list` 來理解。我們使用 `open()` 函數搭配 `with` 敘述開啟 `teams_rowbased.json`，使用 `json` 模組的 `load()` 函數將檔案內容載入，因為 JSON 可能由兩種資料結構組成，輸出物件可能是 `dict` 或 `list` 類別的實例。

In [3]:
json_file_path = "teams_rowbased.json"
with open(json_file_path) as file:
    teams_json = json.load(file)
print(type(teams_json))
print(len(teams_json))
print(type(teams_json[0]))
print(len(teams_json[0]))

<class 'list'>
34
<class 'dict'>
12

CSV 是最廣泛被使用的一種結構化純文字檔案格式，因此還有特定的副檔名 `.csv`，我們使用 `pandas` 模組的 `read_csv()` 函數載入。

In [4]:
movies_csv = pd.read_csv("movies.csv")
print(type(movies_csv))
movies_csv.head()

<class 'pandas.core.frame.DataFrame'>

,id,title,release_year,rating,director,runtime
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142
1,2,The Godfather,1972,9.2,Francis Ford Coppola,175
2,3,The Godfather: Part II,1974,9.0,Francis Ford Coppola,202
3,4,The Dark Knight,2008,9.0,Christopher Nolan,152
4,5,12 Angry Men,1957,9.0,Sidney Lumet,96

HTML 是一種用於建立網頁的標準標記語言，常與 CSS、JavaScript 一起被用於設計網頁、網頁應用程式以及行動應用程式的使用者介面，瀏覽器可以讀取 HTML 檔案，並將其渲染成視覺化網頁，HTML 描述了一個網站的結構語意隨著線索的呈現，使之成為一種標記語言而非程式語言。通常載入 HTML 時會使用 Requests 模組搭配 BeautifulSoup4 模組，前者用於對網頁伺服器發送請求、後者則用於解析 HTML 的內容。

In [5]:
headers = {
    "accept-language": "en,en-US;q=1"
}
r = requests.get("https://www.imdb.com/chart/top", headers=headers)
soup = BeautifulSoup(r.text)
for elem in soup.select(".titleColumn a"):
    print(elem.text)

The Shawshank Redemption
The Godfather
The Dark Knight
The Godfather: Part II
12 Angry Men
Schindler's List
The Lord of the Rings: The Return of the King
Pulp Fiction
The Lord of the Rings: The Fellowship of the Ring
The Good, the Bad and the Ugly
Forrest Gump
Fight Club
Inception
The Lord of the Rings: The Two Towers
Star Wars: Episode V - The Empire Strikes Back
The Matrix
Goodfellas
One Flew Over the Cuckoo's Nest
Se7en
Seven Samurai
It's a Wonderful Life
The Silence of the Lambs
City of God
Saving Private Ryan
Life Is Beautiful
The Green Mile
Interstellar
Star Wars
Terminator 2: Judgment Day
Back to the Future
Spirited Away
Psycho
The Pianist
Léon: The Professional
Parasite
The Lion King
Gladiator
American History X
The Usual Suspects
The Departed
The Prestige
Casablanca
Whiplash
Top Gun: Maverick
The Intouchables
Harakiri
Modern Times
Grave of the Fireflies
Once Upon a Time in the West
Rear Window
Alien
City Lights
Cinema Paradiso
Memento
Apocalypse Now
Indiana Jones and the Raiders of the Lost Ark
Django Unchained
WALL·E
The Lives of Others
Sunset Blvd.
Paths of Glory
The Shining
The Great Dictator
Witness for the Prosecution
Avengers: Infinity War
Aliens
American Beauty
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
Spider-Man: Into the Spider-Verse
The Dark Knight Rises
Oldboy
Joker
Braveheart
Amadeus
Toy Story
Coco
The Boat
Inglourious Basterds
Princess Mononoke
Avengers: Endgame
Once Upon a Time in America
Good Will Hunting
Toy Story 3
Requiem for a Dream
Your Name.
Singin' in the Rain
3 Idiots
Star Wars: Episode VI - Return of the Jedi
2001: A Space Odyssey
Eternal Sunshine of the Spotless Mind
Reservoir Dogs
High and Low
Capernaum
Citizen Kane
Lawrence of Arabia
The Hunt
M
North by Northwest
Vertigo
Amélie
A Clockwork Orange
Come and See
Full Metal Jacket
Double Indemnity
The Apartment
Scarface
Ikiru
The Sting
To Kill a Mockingbird
Taxi Driver
Up
L.A. Confidential
Heat
Metropolis
A Separation
Die Hard
Snatch
Hamilton
Incendies
Indiana Jones and the Last Crusade
Bicycle Thieves
1917
Like Stars on Earth
Downfall
For a Few Dollars More
Batman Begins
Spider-Man: No Way Home
Dangal
The Kid
Some Like It Hot
The Father
All About Eve
Green Book
The Wolf of Wall Street
Judgment at Nuremberg
Ran
Unforgiven
Casino
Pan's Labyrinth
There Will Be Blood
The Sixth Sense
A Beautiful Mind
The Truman Show
Monty Python and the Holy Grail
Yojimbo
The Treasure of the Sierra Madre
Shutter Island
Rashomon
Jurassic Park
The Great Escape
Everything Everywhere All at Once
Kill Bill: Vol. 1
No Country for Old Men
Finding Nemo
The Elephant Man
Chinatown
Raging Bull
Gone with the Wind
V for Vendetta
The Thing
Inside Out
Lock, Stock and Two Smoking Barrels
Dial M for Murder
The Secret in Their Eyes
Howl's Moving Castle
The Bridge on the River Kwai
Three Billboards Outside Ebbing, Missouri
Trainspotting
Warrior
Gran Torino
Fargo
Prisoners
My Neighbor Totoro
Million Dollar Baby
The Gold Rush
Catch Me If You Can
Blade Runner
On the Waterfront
The Third Man
Children of Heaven
Ben-Hur
12 Years a Slave
The General
Wild Strawberries
Before Sunrise
Gone Girl
Harry Potter and the Deathly Hallows: Part 2
The Deer Hunter
In the Name of the Father
The Grand Budapest Hotel
Mr. Smith Goes to Washington
The Wages of Fear
Barry Lyndon
Sherlock Jr.
Memories of Murder
Klaus
Hacksaw Ridge
Room
The Seventh Seal
Wild Tales
The Big Lebowski
Mad Max: Fury Road
How to Train Your Dragon
Mary and Max
Monsters, Inc.
Jaws
The Passion of Joan of Arc
Dead Poets Society
Tokyo Story
Hotel Rwanda
Pather Panchali
Rocky
Platoon
Ford v Ferrari
Stand by Me
The Terminator
Spotlight
Rush
Network
Into the Wild
Logan
The Wizard of Oz
Ratatouille
Groundhog Day
Before Sunset
The Exorcist
The Best Years of Our Lives
The Incredibles
To Be or Not to Be
Rebecca
The Battle of Algiers
The Grapes of Wrath
Hachi: A Dog's Tale
Cool Hand Luke
Amores perros
Pirates of the Caribbean: The Curse of the Black Pearl
La Haine
The 400 Blows
Persona
My Father and My Son
Life of Brian
It Happened One Night
The Sound of Music
Dersu Uzala
The Handmaiden
Aladdin
Jai Bhim
Gandhi
The Help
Beauty and the Beast

In [6]:
for elem in soup.select(".titleColumn a"):
    print(f"""https://www.imdb.com/{elem.get("href")}""")

https://www.imdb.com//title/tt0111161/
https://www.imdb.com//title/tt0068646/
https://www.imdb.com//title/tt0468569/
https://www.imdb.com//title/tt0071562/
https://www.imdb.com//title/tt0050083/
https://www.imdb.com//title/tt0108052/
https://www.imdb.com//title/tt0167260/
https://www.imdb.com//title/tt0110912/
https://www.imdb.com//title/tt0120737/
https://www.imdb.com//title/tt0060196/
https://www.imdb.com//title/tt0109830/
https://www.imdb.com//title/tt0137523/
https://www.imdb.com//title/tt1375666/
https://www.imdb.com//title/tt0167261/
https://www.imdb.com//title/tt0080684/
https://www.imdb.com//title/tt0133093/
https://www.imdb.com//title/tt0099685/
https://www.imdb.com//title/tt0073486/
https://www.imdb.com//title/tt0114369/
https://www.imdb.com//title/tt0047478/
https://www.imdb.com//title/tt0038650/
https://www.imdb.com//title/tt0102926/
https://www.imdb.com//title/tt0317248/
https://www.imdb.com//title/tt0120815/
https://www.imdb.com//title/tt0118799/
https://www.imdb.com//title/tt0120689/
https://www.imdb.com//title/tt0816692/
https://www.imdb.com//title/tt0076759/
https://www.imdb.com//title/tt0103064/
https://www.imdb.com//title/tt0088763/
https://www.imdb.com//title/tt0245429/
https://www.imdb.com//title/tt0054215/
https://www.imdb.com//title/tt0253474/
https://www.imdb.com//title/tt0110413/
https://www.imdb.com//title/tt6751668/
https://www.imdb.com//title/tt0110357/
https://www.imdb.com//title/tt0172495/
https://www.imdb.com//title/tt0120586/
https://www.imdb.com//title/tt0114814/
https://www.imdb.com//title/tt0407887/
https://www.imdb.com//title/tt0482571/
https://www.imdb.com//title/tt0034583/
https://www.imdb.com//title/tt2582802/
https://www.imdb.com//title/tt1745960/
https://www.imdb.com//title/tt1675434/
https://www.imdb.com//title/tt0056058/
https://www.imdb.com//title/tt0027977/
https://www.imdb.com//title/tt0095327/
https://www.imdb.com//title/tt0064116/
https://www.imdb.com//title/tt0047396/
https://www.imdb.com//title/tt0078748/
https://www.imdb.com//title/tt0021749/
https://www.imdb.com//title/tt0095765/
https://www.imdb.com//title/tt0209144/
https://www.imdb.com//title/tt0078788/
https://www.imdb.com//title/tt0082971/
https://www.imdb.com//title/tt1853728/
https://www.imdb.com//title/tt0910970/
https://www.imdb.com//title/tt0405094/
https://www.imdb.com//title/tt0043014/
https://www.imdb.com//title/tt0050825/
https://www.imdb.com//title/tt0081505/
https://www.imdb.com//title/tt0032553/
https://www.imdb.com//title/tt0051201/
https://www.imdb.com//title/tt4154756/
https://www.imdb.com//title/tt0090605/
https://www.imdb.com//title/tt0169547/
https://www.imdb.com//title/tt0057012/
https://www.imdb.com//title/tt4633694/
https://www.imdb.com//title/tt1345836/
https://www.imdb.com//title/tt0364569/
https://www.imdb.com//title/tt7286456/
https://www.imdb.com//title/tt0112573/
https://www.imdb.com//title/tt0086879/
https://www.imdb.com//title/tt0114709/
https://www.imdb.com//title/tt2380307/
https://www.imdb.com//title/tt0082096/
https://www.imdb.com//title/tt0361748/
https://www.imdb.com//title/tt0119698/
https://www.imdb.com//title/tt4154796/
https://www.imdb.com//title/tt0087843/
https://www.imdb.com//title/tt0119217/
https://www.imdb.com//title/tt0435761/
https://www.imdb.com//title/tt0180093/
https://www.imdb.com//title/tt5311514/
https://www.imdb.com//title/tt0045152/
https://www.imdb.com//title/tt1187043/
https://www.imdb.com//title/tt0086190/
https://www.imdb.com//title/tt0062622/
https://www.imdb.com//title/tt0338013/
https://www.imdb.com//title/tt0105236/
https://www.imdb.com//title/tt0057565/
https://www.imdb.com//title/tt8267604/
https://www.imdb.com//title/tt0033467/
https://www.imdb.com//title/tt0056172/
https://www.imdb.com//title/tt2106476/
https://www.imdb.com//title/tt0022100/
https://www.imdb.com//title/tt0053125/
https://www.imdb.com//title/tt0052357/
https://www.imdb.com//title/tt0211915/
https://www.imdb.com//title/tt0066921/
https://www.imdb.com//title/tt0091251/
https://www.imdb.com//title/tt0093058/
https://www.imdb.com//title/tt0036775/
https://www.imdb.com//title/tt0053604/
https://www.imdb.com//title/tt0086250/
https://www.imdb.com//title/tt0044741/
https://www.imdb.com//title/tt0070735/
https://www.imdb.com//title/tt0056592/
https://www.imdb.com//title/tt0075314/
https://www.imdb.com//title/tt1049413/
https://www.imdb.com//title/tt0119488/
https://www.imdb.com//title/tt0113277/
https://www.imdb.com//title/tt0017136/
https://www.imdb.com//title/tt1832382/
https://www.imdb.com//title/tt0095016/
https://www.imdb.com//title/tt0208092/
https://www.imdb.com//title/tt8503618/
https://www.imdb.com//title/tt1255953/
https://www.imdb.com//title/tt0097576/
https://www.imdb.com//title/tt0040522/
https://www.imdb.com//title/tt8579674/
https://www.imdb.com//title/tt0986264/
https://www.imdb.com//title/tt0363163/
https://www.imdb.com//title/tt0059578/
https://www.imdb.com//title/tt0372784/
https://www.imdb.com//title/tt10872600/
https://www.imdb.com//title/tt5074352/
https://www.imdb.com//title/tt0012349/
https://www.imdb.com//title/tt0053291/
https://www.imdb.com//title/tt10272386/
https://www.imdb.com//title/tt0042192/
https://www.imdb.com//title/tt6966692/
https://www.imdb.com//title/tt0993846/
https://www.imdb.com//title/tt0055031/
https://www.imdb.com//title/tt0089881/
https://www.imdb.com//title/tt0105695/
https://www.imdb.com//title/tt0112641/
https://www.imdb.com//title/tt0457430/
https://www.imdb.com//title/tt0469494/
https://www.imdb.com//title/tt0167404/
https://www.imdb.com//title/tt0268978/
https://www.imdb.com//title/tt0120382/
https://www.imdb.com//title/tt0071853/
https://www.imdb.com//title/tt0055630/
https://www.imdb.com//title/tt0040897/
https://www.imdb.com//title/tt1130884/
https://www.imdb.com//title/tt0042876/
https://www.imdb.com//title/tt0107290/
https://www.imdb.com//title/tt0057115/
https://www.imdb.com//title/tt6710474/
https://www.imdb.com//title/tt0266697/
https://www.imdb.com//title/tt0477348/
https://www.imdb.com//title/tt0266543/
https://www.imdb.com//title/tt0080678/
https://www.imdb.com//title/tt0071315/
https://www.imdb.com//title/tt0081398/
https://www.imdb.com//title/tt0031381/
https://www.imdb.com//title/tt0434409/
https://www.imdb.com//title/tt0084787/
https://www.imdb.com//title/tt2096673/
https://www.imdb.com//title/tt0120735/
https://www.imdb.com//title/tt0046912/
https://www.imdb.com//title/tt1305806/
https://www.imdb.com//title/tt0347149/
https://www.imdb.com//title/tt0050212/
https://www.imdb.com//title/tt5027774/
https://www.imdb.com//title/tt0117951/
https://www.imdb.com//title/tt1291584/
https://www.imdb.com//title/tt1205489/
https://www.imdb.com//title/tt0116282/
https://www.imdb.com//title/tt1392214/
https://www.imdb.com//title/tt0096283/
https://www.imdb.com//title/tt0405159/
https://www.imdb.com//title/tt0015864/
https://www.imdb.com//title/tt0264464/
https://www.imdb.com//title/tt0083658/
https://www.imdb.com//title/tt0047296/
https://www.imdb.com//title/tt0041959/
https://www.imdb.com//title/tt0118849/
https://www.imdb.com//title/tt0052618/
https://www.imdb.com//title/tt2024544/
https://www.imdb.com//title/tt0017925/
https://www.imdb.com//title/tt0050986/
https://www.imdb.com//title/tt0112471/
https://www.imdb.com//title/tt2267998/
https://www.imdb.com//title/tt1201607/
https://www.imdb.com//title/tt0077416/
https://www.imdb.com//title/tt0107207/
https://www.imdb.com//title/tt2278388/
https://www.imdb.com//title/tt0031679/
https://www.imdb.com//title/tt0046268/
https://www.imdb.com//title/tt0072684/
https://www.imdb.com//title/tt0015324/
https://www.imdb.com//title/tt0353969/
https://www.imdb.com//title/tt4729430/
https://www.imdb.com//title/tt2119532/
https://www.imdb.com//title/tt3170832/
https://www.imdb.com//title/tt0050976/
https://www.imdb.com//title/tt3011894/
https://www.imdb.com//title/tt0118715/
https://www.imdb.com//title/tt1392190/
https://www.imdb.com//title/tt0892769/
https://www.imdb.com//title/tt0978762/
https://www.imdb.com//title/tt0198781/
https://www.imdb.com//title/tt0073195/
https://www.imdb.com//title/tt0019254/
https://www.imdb.com//title/tt0097165/
https://www.imdb.com//title/tt0046438/
https://www.imdb.com//title/tt0395169/
https://www.imdb.com//title/tt0048473/
https://www.imdb.com//title/tt0075148/
https://www.imdb.com//title/tt0091763/
https://www.imdb.com//title/tt1950186/
https://www.imdb.com//title/tt0092005/
https://www.imdb.com//title/tt0088247/
https://www.imdb.com//title/tt1895587/
https://www.imdb.com//title/tt1979320/
https://www.imdb.com//title/tt0074958/
https://www.imdb.com//title/tt0758758/
https://www.imdb.com//title/tt3315342/
https://www.imdb.com//title/tt0032138/
https://www.imdb.com//title/tt0382932/
https://www.imdb.com//title/tt0107048/
https://www.imdb.com//title/tt0381681/
https://www.imdb.com//title/tt0070047/
https://www.imdb.com//title/tt0036868/
https://www.imdb.com//title/tt0317705/
https://www.imdb.com//title/tt0035446/
https://www.imdb.com//title/tt0032976/
https://www.imdb.com//title/tt0058946/
https://www.imdb.com//title/tt0032551/
https://www.imdb.com//title/tt1028532/
https://www.imdb.com//title/tt0061512/
https://www.imdb.com//title/tt0245712/
https://www.imdb.com//title/tt0325980/
https://www.imdb.com//title/tt0113247/
https://www.imdb.com//title/tt0053198/
https://www.imdb.com//title/tt0060827/
https://www.imdb.com//title/tt0476735/
https://www.imdb.com//title/tt0079470/
https://www.imdb.com//title/tt0025316/
https://www.imdb.com//title/tt0059742/
https://www.imdb.com//title/tt0071411/
https://www.imdb.com//title/tt4016934/
https://www.imdb.com//title/tt0103639/
https://www.imdb.com//title/tt15097216/
https://www.imdb.com//title/tt0083987/
https://www.imdb.com//title/tt1454029/
https://www.imdb.com//title/tt0101414/

## 使用 Python 載入試算表

試算表是類比紙本計算表格的電腦軟體，由許多列與欄所構成的儲存格，其中可以存放數值、算式或文字，常見的試算表軟體有 Microsoft Excel、macOS Numbers 與 Google Sheets。試算表的檔案為一個活頁簿（Workbook）、活頁簿中可以有多個試算表（Spreadsheets），我們使用 `pandas` 模組的 `read_excel()` 函數預設讀取第零張試算表（左邊數來第一張）。

In [7]:
excel_file_path = "imdb.xlsx"
movies_xlsx = pd.read_excel(excel_file_path)
print(type(movies_xlsx))
movies_xlsx.head()

<class 'pandas.core.frame.DataFrame'>

,id,title,release_year,rating,director,runtime
0,1.0,The Shawshank Redemption,1994.0,9.3,Frank Darabont,142.0
1,2.0,The Godfather,1972.0,9.2,Francis Ford Coppola,175.0
2,3.0,The Godfather: Part II,1974.0,9.0,Francis Ford Coppola,202.0
3,4.0,The Dark Knight,2008.0,9.0,Christopher Nolan,152.0
4,5.0,12 Angry Men,1957.0,9.0,Sidney Lumet,96.0

由於活頁簿中可以有多個試算表的設計，載入之前建議先使用 `pandas` 模組的 `ExcelFile` 類別的 `sheet_names` 屬性檢視活頁簿中有幾個試算表。

In [8]:
excel_file = pd.ExcelFile(excel_file_path)
excel_file.sheet_names

['movies', 'casting', 'actors']

在 `pandas` 模組的 `read_excel()` 函數指定參數 `sheet_name` 載入特定試算表，可以接受試算表名稱、亦能輸入整數（由左邊從零開始數來第幾張試算表）。

In [9]:
casting_xlsx = pd.read_excel(excel_file_path, sheet_name="casting")
actors_xlsx = pd.read_excel(excel_file_path, sheet_name=2)
casting_xlsx.head()

   movie_id  actor_id  ord
0       1.0    2853.0  1.0
1       1.0    2097.0  2.0
2       1.0     333.0  3.0
3       1.0    3029.0  4.0
4       1.0     533.0  5.0

In [10]:
actors_xlsx.head()

    id                name
0  1.0          Aamir Khan
1  2.0       Aaron Eckhart
2  3.0  Abbas-Ali Roomandi
3  4.0           Abbey Lee
4  5.0       Abbie Cornish

## 使用 Python 載入關聯式資料庫管理系統中的資料表

關聯式資料庫（Relational database）是基於關聯模型所建構的資料庫，是儲存在電腦中的資料集合。一個資料庫中通常會有多個資料表（Table）能夠藉助集合運算（Set operation）等數學方法來處理資料表之間的操作和關聯，也能夠用來表示現實世界中的商業邏輯，並能夠接受結構化查詢語言 SQL 來進行檢索和操作。我們使用 `sqlite3` 模組的 `connect()` 函數建立與資料庫的連線，再運用結構化查詢語言 SQL 搭配 `pandas` 模組的 `read_sql()` 函數載入，資料庫使用完畢之後將連線關閉。

In [11]:
connection = sqlite3.connect("imdb.db")
query = """
SELECT *
  FROM movies;
"""
movies_db = pd.read_sql(query, connection)
movies_db.head()

,id,title,release_year,rating,director,runtime
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142
1,2,The Godfather,1972,9.2,Francis Ford Coppola,175
2,3,The Godfather: Part II,1974,9.0,Francis Ford Coppola,202
3,4,The Dark Knight,2008,9.0,Christopher Nolan,152
4,5,12 Angry Men,1957,9.0,Sidney Lumet,96

In [12]:
query = """
SELECT *
  FROM casting;
"""
casting_db = pd.read_sql(query, connection)
casting_db.head()

   movie_id  actor_id  ord
0         1      2853    1
1         1      2097    2
2         1       333    3
3         1      3029    4
4         1       533    5

In [13]:
query = """
SELECT *
  FROM actors;
"""
actors_db = pd.read_sql(query, connection)
actors_db.head()

   id                name
0   1          Aamir Khan
1   2       Aaron Eckhart
2   3  Abbas-Ali Roomandi
3   4           Abbey Lee
4   5       Abbie Cornish

In [14]:
connection.close()

在認識了如何使用 Python 載入純文字檔案、試算表與關聯式資料庫中的資料表之後，第三十一週約維安計畫：使用 Python 載入資料來到尾聲，希望您也和我一樣期待下一篇文章。

對於這篇文章有什麼想法呢？喜歡😻、留言🙋‍♂️或者分享🙌